### ISSUE TITLE
private key cannot be imported

### ISSUE THREAD

**Issue by oddyutza** [bakurits/mattermost-plugin-anonymous#61] opened 2020-10-07 07:29 UTC
while using /anonymous keypair --export i've recevied the private key, i;ve copied it
while using /anonymous keypair --overwrite i've paste it
-> received " Invalid Key " - each time
can be reproduced as per abobe
it happens with any account on web or with app wrapper

**Comment by bakurits** [comment] 2020-10-07 07:33
Duplicate of #60

**Closed** 2020-10-07 07:39 UTC
Labels: bug
